### PR TITLE
Update relationships.js

### PR DESCRIPTION
**Pull request by markgmilner**
Set population to use exec to invoke callback instead of run.

### CODE REVIEW

**Comment by markgmilner** [comment]
What do you think about adding some mappedBy functionality to this module kind of like doctrine: http://docs.doctrine-project.org/en/2.0.x/reference/association-mapping.html.

This is very useful when the children of a model have a reference back to the parent but the parent does not have an array of references to the children. A lot of times I need to load the children from the parent, and this current implementation doesn't allow for this.

I have adding this functionality but will wait to pr it until I test it out for a bit today.

To use this functionality, in the schema you would define a reference as such:

``` javascript
userSchema.hasMany('members', {through : 'members', mappedBy : 'user', model : memberEntity});
```

The model option is necessary in order to make queries from the child model rather than the parent model, there might be a better way to do this.

Edit:
I have also been working on adding in some functionality to populate subfields of these children. For instance:

``` javascript
user.members.populate("account", function(err, results){});
```

**Comment by jcspencer** [comment]
LGTM, just add some unit tests, and I'll merge your changes :+1:

**Comment by jcspencer** [comment]
Also, async needs to be added to dependencies

**Comment by markgmilner** [comment]
Of course, apologies for the incomplete pr. I really should have made this an issue instead of a pr.  I was just curious what you thought about the idea.  I had to add in this functionality for my own project.  It seems to be working pretty well. I'll add in the necessities and comment on all my changes when ready.

**Comment by markgmilner** [comment]
What version of should and expresso are you using.  I can't seem to get the tests to run.

**Pull request closed without merging**
