### PR TITLE
setParent option to prevent adding child ids to parent documents in hasMany

### PR DESCRIPTION
**Pull request by jonstorer**
setParent option allows a `hasMany` association to not save its child ids on itself.
- mongo-relation queries children by parent's id on child as a foreign key
- Mongoose populate on a Model will not populate children
- mongoose populate on a document will return an error (use find)
- I believe we can bring `doc.populate` back eventually. Probably after we've moved to mongoose-long & our own types (instead of adding to MongooseArray.prototype)

We should discuss keeping a separate branch until the breaking changes are resolved.

### CODE REVIEW

**Comment by jcspencer** [comment]
In terms of a `.hasOne()` `.create()` method, I think there is no document, we set a `child.create()` method on the parent document using virtuals, or else just return the saved child document.

**Comment by jonstorer** [comment]
Agreed. IMO, hasOne and hasMany can both be virtuals. 

While the current functionality of hasMany can be attained with an unpaired habtm. 

Thoughts?
—
Jonathon

**Comment by jcspencer** [comment]
That sounds good! I think these features should all be moved into a v1.0.0 branch. That way, we can add breaking changes without effecting current users.

On the topic of Virtuals, I think moving as much as we can to virtuals would be a big positive, as it would bring us closer to allowing mongo-relation to be used as a Mongoose Plugin, because it would only need access to the Schema.

**Comment by jcspencer** [comment]
I've merged this PR into the v1.0.0 branch. Thanks!

**Pull request closed without merging**
